// <auto-generated />
using System;
using FoodOffer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOffer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240802223503_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Address", b =>
                {
                    b.Property<int>("add_ref_id")
                        .HasColumnType("int");

                    b.Property<string>("add_ref_type")
                        .HasColumnType("varchar(1)");

                    b.Property<short>("add_item")
                        .HasColumnType("smallint");

                    b.Property<short>("add_cit_cod")
                        .HasColumnType("smallint");

                    b.Property<short>("add_cou_cod")
                        .HasColumnType("smallint");

                    b.Property<string>("add_desc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("add_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("add_obs")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<short>("add_ste_cod")
                        .HasColumnType("smallint");

                    b.HasKey("add_ref_id", "add_ref_type", "add_item");

                    b.ToTable("addresses");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Advertising", b =>
                {
                    b.Property<int>("adv_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<short>("adv_ads_cod")
                        .HasColumnType("smallint");

                    b.Property<short>("adv_cat_cod")
                        .HasColumnType("smallint");

                    b.Property<int>("adv_com_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("adv_create_date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("adv_delete_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("adv_desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("adv_price")
                        .HasColumnType("double");

                    b.Property<short>("adv_prl_cod")
                        .HasColumnType("smallint");

                    b.Property<string>("adv_title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("adv_update_date")
                        .HasColumnType("datetime(6)");

                    b.HasKey("adv_id");

                    b.ToTable("advertisings");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Advertising_address", b =>
                {
                    b.Property<int>("aad_adv_id")
                        .HasColumnType("int");

                    b.Property<int>("aad_adv_com_id")
                        .HasColumnType("int");

                    b.Property<short>("aad_add_item")
                        .HasColumnType("smallint");

                    b.HasKey("aad_adv_id", "aad_adv_com_id", "aad_add_item");

                    b.ToTable("advertisings_address");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Advertising_Attribute", b =>
                {
                    b.Property<int>("ada_adv_id")
                        .HasColumnType("int");

                    b.Property<short>("ada_atr_cod")
                        .HasColumnType("smallint");

                    b.Property<string>("ada_value")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("ada_adv_id", "ada_atr_cod");

                    b.ToTable("advertising_attributes");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Advertising_Category", b =>
                {
                    b.Property<short>("cat_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("cat_desc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("cat_cod");

                    b.ToTable("advertising_categories");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Advertising_Image", b =>
                {
                    b.Property<int>("adi_adv_id")
                        .HasColumnType("int");

                    b.Property<short>("adi_item")
                        .HasColumnType("smallint");

                    b.Property<string>("adi_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("adi_path")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("adi_adv_id", "adi_item");

                    b.ToTable("advertising_images");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Advertising_State", b =>
                {
                    b.Property<short>("ads_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("ads_desc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ads_cod");

                    b.ToTable("advertising_states");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Advertising_Time_Set", b =>
                {
                    b.Property<int>("ats_adv_id")
                        .HasColumnType("int");

                    b.Property<short>("ats_day")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("ats_end_1")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("ats_end_2")
                        .HasColumnType("time(6)");

                    b.Property<string>("ats_nextday_1")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ats_nextday_2")
                        .HasColumnType("varchar(1)");

                    b.Property<TimeSpan>("ats_start_1")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("ats_start_2")
                        .HasColumnType("time(6)");

                    b.HasKey("ats_adv_id", "ats_day");

                    b.ToTable("advertising_time_settings");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Attribute", b =>
                {
                    b.Property<short>("atr_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<short>("atr_atc_cod")
                        .HasColumnType("smallint");

                    b.Property<string>("atr_desc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("atr_cod");

                    b.ToTable("attributes");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Attributes_Category", b =>
                {
                    b.Property<short>("atc_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("atc_desc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("atc_cod");

                    b.ToTable("attribute_categories");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_City", b =>
                {
                    b.Property<short>("cit_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<short>("cit_cou_cod")
                        .HasColumnType("smallint");

                    b.Property<string>("cit_desc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<short>("cit_ste_cod")
                        .HasColumnType("smallint");

                    b.HasKey("cit_cod");

                    b.ToTable("cities");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Commerce", b =>
                {
                    b.Property<int>("com_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("com_cell_phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<short>("com_cot_cod")
                        .HasColumnType("smallint");

                    b.Property<string>("com_mail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("com_name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("com_phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("com_usr_id")
                        .HasColumnType("int");

                    b.Property<string>("com_web_url")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("com_id");

                    b.ToTable("commerces");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Commerce_Attribute", b =>
                {
                    b.Property<int>("coa_com_id")
                        .HasColumnType("int");

                    b.Property<short>("coa_atr_id")
                        .HasColumnType("smallint");

                    b.Property<string>("coa_value")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.HasKey("coa_com_id", "coa_atr_id");

                    b.ToTable("commerce_attributes");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Commerce_Image", b =>
                {
                    b.Property<int>("coi_com_id")
                        .HasColumnType("int");

                    b.Property<short>("coi_item")
                        .HasColumnType("smallint");

                    b.Property<string>("coi_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("coi_path")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("coi_com_id", "coi_item");

                    b.ToTable("commerce_images");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Commerce_Type", b =>
                {
                    b.Property<short>("cot_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("cot_desc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("cot_cod");

                    b.ToTable("commerce_types");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Country", b =>
                {
                    b.Property<short>("cou_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("cou_desc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("cou_cod");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Identification_Type", b =>
                {
                    b.Property<short>("ide_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("ide_desc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ide_cod");

                    b.ToTable("identification_types");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_Priority_level", b =>
                {
                    b.Property<short>("prl_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("prl_desc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("prl_cod");

                    b.ToTable("priority_levels");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_State", b =>
                {
                    b.Property<short>("ste_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<short>("ste_cou_cod")
                        .HasColumnType("smallint");

                    b.Property<string>("ste_desc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ste_cod");

                    b.ToTable("states");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_User", b =>
                {
                    b.Property<int>("usr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("usr_cell_phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<short?>("usr_ide_cod")
                        .HasColumnType("smallint");

                    b.Property<string>("usr_ide_num")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("usr_mail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("usr_name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("usr_phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<short>("usr_ust_cod")
                        .HasColumnType("smallint");

                    b.HasKey("usr_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_User_Login_Data", b =>
                {
                    b.Property<int>("uld_usr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("uld_email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("uld_pwd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("uld_salt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("uld_usr_id");

                    b.ToTable("user_login_data");
                });

            modelBuilder.Entity("clasificados.Infraestructure.DbContextConfig.DbModels.Db_User_Type", b =>
                {
                    b.Property<short>("ust_cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("ust_desc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ust_cod");

                    b.ToTable("user_types");
                });
#pragma warning restore 612, 618
        }
    }
}
